image:
  repository: arckive-operator
  tag: dev
  pullPolicy: IfNotPresent

workerImage:
  repository: arckive-worker
  tag: dev

logLevel: info
resyncIntervalMs: 300000

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 256Mi
