apiVersion: arclight.dev/v1alpha1
kind: Indexer
metadata:
  name: demo
spec:
  network:
    chainId: 31337
    rpc: ["ws://anvil:8545", "http://anvil:8545"]
    finalityTag: latest
  storage:
    mode: External
    external:
      dsnSecretRef: { name: pg-dsn, key: url }
  contracts:
    - name: emitter
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      abi:
        configMapRef: { name: emitter-abi, key: abi.json }
      startBlock: 0
      events: []
  polling:
    batchBlocks: 100
    intervalMs: 1000
