#!/usr/bin/env bash
# Generates a single-file install manifest: Namespace + CRD + operator (helm template).
# The output is published as https://arckive.org/install.yaml; do not edit it by hand.
#
# Usage: scripts/build-install.sh
#   REGISTRY=ghcr.io/goguzgungor TAG=latest OUT=install.yaml (defaults)
set -euo pipefail

REGISTRY="${REGISTRY:-ghcr.io/goguzgungor}"
TAG="${TAG:-latest}"
OUT="${OUT:-install.yaml}"

cd "$(dirname "$0")/.."

{
  echo "# Arckive (arckive) install — generated by scripts/build-install.sh; do not edit by hand."
  echo "# kubectl apply -f https://arckive.org/install.yaml"
  echo "---"
  cat <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: arckive-system
  labels:
    app.kubernetes.io/name: arckive-operator
EOF
  for crd in charts/arckive/crds/*.yaml; do
    echo "---"
    cat "$crd"
  done
  helm template arckive charts/arckive \
    --namespace arckive-system \
    --set image.repository="${REGISTRY}/arckive-operator" \
    --set image.tag="${TAG}" \
    --set image.pullPolicy=Always \
    --set workerImage.repository="${REGISTRY}/arckive-worker" \
    --set workerImage.tag="${TAG}"
} > "$OUT"

echo "wrote: ${OUT} (registry=${REGISTRY} tag=${TAG})"
